### ISSUE TITLE
EMF-Datenbank jetzt "verschlüsselt"

### ISSUE THREAD

**Issue by stefanw** [dahilzen/Mobilfunk-Scrape#1]
Die BNetzA hat die Antworten der Datenbank jetzt verschlüsselt, aber natürlich dem Client den Key gegeben, damit man noch was sieht.

Ich habe den Scraper dafür mal angepasst und aus Versehen quasi neu geschrieben.

https://github.com/stefanw/bnetza-emf-scraper

Just FYI

**Comment by dahilzen** [comment]
Großes Kino, vielen Dank dafür!
